name = "Lotsa Modsa"
author = "Winsweep"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48c6e487234e6b518af1981fad20b2c0b9c3c68fbbea2e200482f6d7513c9f8f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
