name = "Lotsa Modsa"
author = "Winsweep"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2abcd01a8cdfb547412979ddc99d90b92e4660d568db5b3372314404b5824099"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
