name = "Lotsa Modsa"
author = "Winsweep"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64f7f2bef007dbc282de6b960463b886290db022a41d941c954cfac2fda72060"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
